### ISSUE TITLE
超分后图像尺寸问题

### ISSUE THREAD

**Issue by sunyclj** [XPixelGroup/ClassSR#41]
您好，按照您的测试流程测试test2K文件夹下的图片，x4超分，超分后的图像尺寸与HR尺寸不一致，如1299.png：
![50CA64B3-C033-4b65-9250-6CD94111F243](https://user-images.githubusercontent.com/44860428/150761592-4e890ab0-a590-4f64-abf9-51a705b671de.png)
![BC3834A4-7302-4128-B3F0-91537E49B637](https://user-images.githubusercontent.com/44860428/150761658-9adc4b70-2f40-4470-8142-698ef435a4bd.png)
请问这种情况是什么原因呢？既然尺寸不一致，psnr指标如何计算的呢？

**Comment by Xiangtaokong** [comment]
classsr会把整图裁剪成一些小图然后恢复再拼接，小图的大小是128*128 步长 16，剩下的不够一张小图，就相当于“裁剪”了边缘。计算的话就是在拼起来之后的那个区域计算。

如果你只是想要图，可以直接跑RCAN之类的单模型，就不会有这个问题了

**Comment by sunyclj** [comment]
@Xiangtaokong 谢谢您的回答，不过论文中描述patch_size=32，您说的图像块128*128步长16是什么意思呢？分类的时候图像块的大小为128*128吗？且相邻图像块之间有重复的区域？

**Comment by Xiangtaokong** [comment]
LR 32*32 步长4 超分之后就是128*128 步长16啦，是的 有部分重合，拼接的时候要平均一下，防止明显切割痕迹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 中午11:11
收件人: ***@***.***&gt;;
抄送: "Xiangtao ***@***.******@***.***&gt;;
主题: Re: [Xiangtaokong/ClassSR] 超分后图像尺寸问题 (Issue #41)




 
@Xiangtaokong 谢谢您的回答，不过论文中描述patch_size=32，您说的图像块128128步长16是什么意思呢？分类的时候图像块的大小为128128吗？且相邻图像块之间有重复的区域？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunyclj** [comment]
@Xiangtaokong 是否可以不重合分割图像块呢？

**Comment by sunyclj** [comment]
@Xiangtaokong 麻烦请教您几个问题：
1、论文中指出模型包含不同通道数的三个分支，分支数是如何确定的？
2、三个分支是分别训练并得到三个预训练模型吗？测试的时候根据分类结果调用网络分支时，是加载对应的预训练模型进行推理吗？
3、训练过程是先进行train a single branch，后进行train ClassSR吗？

**Comment by Xiangtaokong** [comment]
先训支路再一起训练，这几个问题文章里都写得很清楚了，训练策略那一章节



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 下午2:54
收件人: ***@***.***&gt;;
抄送: "Xiangtao ***@***.******@***.***&gt;;
主题: Re: [Xiangtaokong/ClassSR] 超分后图像尺寸问题 (Issue #41)




 
@Xiangtaokong 麻烦请教您几个问题：
 1、论文中指出模型包含不同通道数的三个分支，分支数是如何确定的？
 2、三个分支是分别训练并得到三个预训练模型吗？测试的时候根据分类结果调用网络分支时，是加载对应的预训练模型进行推理吗？
 3、训练过程是先进行train a single branch，后进行train ClassSR吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
