### ISSUE TITLE
tensor问题

### ISSUE THREAD

**Issue by Charles-258** [XPixelGroup/ClassSR#44]
大佬您好，我在训练RCAN的一个branch的时候经常会在八倍上出现tensor上的问题，但是其他的都能正常的跑，改了很久都没有改出来，不知道您是否方便分享一下八倍的RCAN的三个分支的预训练模型，很抱歉麻烦您！

**Comment by Xiangtaokong** [comment]
抱歉，我没训练过八倍超分的ClassSR

**Comment by Charles-258** [comment]
您好，我是王仡垚，您的邮件我已经收到，我会尽快回复。
