### ISSUE TITLE
请问一下论文里提到的baseline的结果是如何获得的？

### ISSUE THREAD

**Issue by wangqiim** [XPixelGroup/ClassSR#45]
请问一下如何复现论文中的baseline结果
FSRCNN-O论文里提到baseline是25.61dB。然后我试了两种方式来复现：（ 1）用你的训练集训自己FSRCNN然后再跑test2k（与classsr的区别是直接对整张图超分，没有分解和组合图片的操作）；（2）用你提供的预训练的classsr模型，然后测试时候强制都分到最复杂的超分分支上。
这两种结果获得的PSNR都比论文里提到的FSRCNN-O要高，方式（1）高0.4，方式（2）高0.2。

（我另外试了其他几个backbone，复现Original module的时候都有挺大差异的，因此想了解一下论文中的baseline是如何获得的 :)

**Comment by Xiangtaokong** [comment]
FSRCNN-O，是使用这套代码训练branch，但是使用全量数据，训练100w代得到的。（ClassSR是支路50w代预训练，然后联合训练小于50w代，保证对比的公平）
测试的时候，是要切割的。在ClassSR框架里，当时使用的方法是加载这个模型到第三个支路，然后让所有图片走第三个支路。

**Comment by Xiangtaokong** [comment]
FSRCNN-O，是使用这套代码训练branch，但是使用全量数据，训练100w代得到的。（ClassSR是支路50w代预训练，然后联合训练小于50w代，保证对比的公平）

测试的时候，是要切割的，因为文章的背景中切割就是必要的一步。在ClassSR框架里，当时使用的方法是加载这个模型到第三个支路，然后让所有图片走第三个支路。

你提到的方法二我没有测试过，因为这个branch3不能作为-O，它在理想状态下，其实是在最复杂数据上训练的FSRCNN。

其他baseline获取方法都与上述FSRCNN-O一致

**Comment by wangqiim** [comment]
> FSRCNN-O，是使用这套代码训练branch，但是使用全量数据，训练100w代得到的。（ClassSR是支路50w代预训练，然后联合训练小于50w代，保证对比的公平）
> 
> 测试的时候，是要切割的，因为文章的背景中切割就是必要的一步。在ClassSR框架里，当时使用的方法是加载这个模型到第三个支路，然后让所有图片走第三个支路。
> 
> 你提到的方法二我没有测试过，因为这个branch3不能作为-O，它在理想状态下，其实是在最复杂数据上训练的FSRCNN。
> 
> 其他baseline获取方法都与上述FSRCNN-O一致

了解了，谢谢
