### ISSUE TITLE
训练第三步

### ISSUE THREAD

**Issue by dfpdl** [XPixelGroup/ClassSR#51]
您好，想请教您两个问题
问题群1：训练第三步的时候，释放三个分支的参数之后，除了用分类的3个loss，训练三个分支的SR的pix的loss是否也要加上？
问题2：训练完第二步，然后在释放三个分支的参数的时候，是不是直接把第二步训练完的模型直接作为第三步的预训练的模型就可以？谢谢您

**Comment by Xiangtaokong** [comment]
感谢关注~
1.pix loss是要加的，但不是三个支路分别监督，是监督三合一之后最后的结果。
2.是的，直接用第二部的模型，放到总的那里加载即可

**Comment by dfpdl** [comment]
我是用的自己的图像数据用的您的网络（我是自己改成classSR-SPSR，我用的SPSR这篇文章的网络结构和您的结合起来），现在训练第二步的时候（固定分支的参数阶段）出现了几个问题，想请教下您，谢谢；
1.您的第二步训练的输入数据也是提前剪切成32*32的吗？然后验证集是不用剪切的，我的训练输入是64*64的，step是32，是不是只改一下配置文件中的step和patchsize就可以？
2.我训练第二步的时候，psnr的值，一直保持不变，您知道什么原因吗？下面是我跑的截图，您看一下。（忽略FLOP和percent的值，我自己写死 的），每一张图片剪切成N个块时，每张图像剪切的所有块只经过一个分支，并且每次经过该分支时，PSNR的值都是一样的，这是什么原因呢？十分感谢！！！！
![8768727138e36afc22ce0fc250cc31ec_1.png](https://temp.img.zlogs.net/22/202210271666852473.png)

**Comment by Xiangtaokong** [comment]
1.test配置文件中的patchsize与训练图的尺寸保持一致。step是控制测试时用多大overlap，与训练无关。
2.这个其实说明你的各种配置是没问题的，是收敛到了全都选择最大支路了，所以PSNR也不会变（因为支路不会被更新）。可以增大averageloss的权重，让他们分开。

**Comment by dfpdl** [comment]
是这样的，我加大了averageloss的权重也没有作用，我出现的情况是，验证集的所有剪切的patch块在每次iteration迭代的时候都走同一个分支（看了下并不是只走最大支路），每次iteration选择的支路不同，但是同一个iteration走的确实是同一个分支，然后我验证了自己的数据集也没有问题，然后我的数据用您的预训练模型就没有问题，可能我自己的预训练模型有问题?(SPSR超分辨模型作为预训练网络），预训练网络是需要有什么注意的吗？现在试了很多方法都解决不了这个问题，十分感谢作者能否帮忙解答下这个问题？

**Comment by dfpdl** [comment]
训练第二步的时候，是否和预训练模型有关系呢？我的第二步在调试的时候发现分类的grad后面就变成了0，也就是分类的参数不在更新了，导致了这个问题，一直找不到是什么原因，除了和您的预训练模型不一致，其他的都几乎一致，所以想请作者能否帮忙给解决下这个问题，十分感谢

**Comment by Xiangtaokong** [comment]
你可以尝试输出每次分类的概率，应该在结构里有，我猜可能是【0.333，0.333，0.333】然后都没更新，所以随机选了一个支路走。

这样的话很可能是分类模块没有更新。你要注意改变结构的时候，三个预训练模型的结果最后要乘加在一起，要不就是一个if选择支路而不是梯度回传。看看是不是这个问题

**Comment by dfpdl** [comment]
非常感谢作者，这个问题解决了，但是我在训练第二步的时候classfier好像不收敛，网络一会走三个分支，一会走前两个分支，有的时候只走后面两个分支，请问这是什么原因呢？十分感谢。您看下我的训练的结果是不是正确的？但是好像不收敛。
![4c52467305d1273049c37b267163055](https://user-images.githubusercontent.com/54699781/199220831-7aa80e49-1ab4-4ab8-95f6-47d12447e054.png)

**Comment by Xiangtaokong** [comment]
训练iter太少了，如果调试这样是可以的，但要收敛到稳定基本还是要几万iter才行的，初期可能会出现波动很大的结果，目前看来正常

**Comment by dfpdl** [comment]
现在训练了大概一万多个iteration，然后后面的PSNR很多都一样的，而且简单的分支走的比较少，这样是正常的吗？是已经收敛了吗？十分感谢作者。
![27e1e94a4a392a540924349c2b5ab87](https://user-images.githubusercontent.com/54699781/199485500-020de20d-b23b-4561-aaa5-e21e866edff5.png)

**Comment by Xiangtaokong** [comment]
1.不用每个iter都valid一次，这样会让训练变很慢
2.这个PSNR是60多的意思吗？是不是太高了，当然这跟你的数据有关
3.一般训练稳定得10W+？不同任务情况也不一定一样，但我觉得1W是有点少的。你可以看一下训练和loss曲线，如果长时间变化不大也可以判断为收敛，需要自己判断

**Comment by dfpdl** [comment]
非常感谢作者
1.我这个输出之前是为了调试代码弄的，后来正式训练的时候就忘了关了，非常感谢提醒，
2.这个PSNR我只用了两张验证图像，是指两张图像的PSNR的值加在一起的吗？我用的是自己的遥感图像，以及后面的预训练模型，我是自己训练的其他的超分辨模型。
3.刚才看了下总的loss的值，好像波动比较大，一直没有处于一个稳定的状态，但是好像PSNR不怎么变动？这是正常的还是哪里的设置有问题？十分感谢

**Comment by dfpdl** [comment]
代码中，三个loss的权重值默认给的是1000,0。5和3，而论文里面给的是2000,1和6，我直接用的您代码默认的设置，是否需要更改过来？十分感谢

**Comment by dfpdl** [comment]
好的，谢谢您。我现在遇到了一个问题，就是，我的分类分反了是什么情况呀？就是简单的被分成难得，难的被分成简单的是什么情况呀？十分感谢。还有第二个问题，就是我在训练第三步的时候，把fix_SR_module=false，然后把第二步训练完的模型放到resume_state下，会提示我resume_state['iter']key error的问题。十分感谢作者

**Comment by dfpdl** [comment]
作者您好，我这几天改了下自己的预训练模型，然后发现一个问题，作者能否给解答下疑惑呢？十分感谢，就是我的代码更倾向于走得到PSNR最差的那个分支，跟哪个分支是不是简单还是复杂没有关系，哪个分支得到的效果越差，就越倾向于走这个分支，不知道作者是否遇到过这个问题？这个问题怎么解决呢？十分感谢作者

**Comment by Xiangtaokong** [comment]
> 好的，谢谢您。我现在遇到了一个问题，就是，我的分类分反了是什么情况呀？就是简单的被分成难得，难的被分成简单的是什么情况呀？十分感谢。还有第二个问题，就是我在训练第三步的时候，把fix_SR_module=false，然后把第二步训练完的模型放到resume_state下，会提示我resume_state['iter']key error的问题。十分感谢作者

应该是把模型路径放在 network加载，而不是加载state

什么是结果差的分支，他们有简单复杂关系吗？得到最差也可能是最复杂分支啊…因为他处理的数据最难所以一般结果是最差的
