### ISSUE TITLE
Questions about classification method

### ISSUE THREAD

**Issue by HaoDot** [XPixelGroup/ClassSR#53]
Hi @Xiangtaokong , a nice work for SR acceleration. I have some questions. Could you help me explain these? Thanks ahead.

- Conflict between the Class loss and Average loss
It seems that the Class-loss is designed to teach the Class-Module to predict the probability of branches unevenly, while the Average-loss is trying to teach the Class-Module to predict probability evenly. I think that the Class-Module tries to strike a balance between certain routing and uncertain routing. Could you help me explain this trade off?
- Loss curve during the training Class-Module
Besides, during the training, I find it that Class-loss decreases obviously. But Average-loss changes smoothly. Is this obversation normal?
    ![de9da495393269a2fcc8461f881cb78](https://user-images.githubusercontent.com/75289266/209902322-27e8ea21-0044-49e5-a16a-1b369c0719bd.png)
    ![a4e7e1ccfd13ec16cafe747c68204b9](https://user-images.githubusercontent.com/75289266/209902342-3822b10c-96a3-4e35-ae09-14ba4ea4630d.png)
Waiting for your reply! Thanks for your time!

**Comment by Xiangtaokong** [comment]
Thank for your attention.


Class loss makes the classification probability uneven such as [0,0,1]. It constraints the probability of a sample（a sub image）.


Average loss makes the classification results even among a batch such [32,32,32] of batch size 96.


They are not on the same level. We should first satisfy class loss to make sure the rationality and than consider average loss.


The losses are normal, you can understand the loss curve according the above explain.



---Original---
From: "Hao ***@***.***&gt;
Date: Thu, Dec 29, 2022 12:12 PM
To: ***@***.***&gt;;
Cc: "Xiangtao ***@***.******@***.***&gt;;
Subject: [XPixelGroup/ClassSR] Questions about classification method (Issue#53)




 
Hi @Xiangtaokong , a nice work for SR acceleration. I have some questions. Could you help me explain these? Thanks ahead.
  
Conflict between the Class loss and Average loss
 It seems that the Class-loss is designed to teach the Class-Module to predict the probability of branches unevenly, while the Average-loss is trying to teach the Class-Module to predict probability evenly. I think that the Class-Module tries to strike a balance between certain routing and uncertain routing. Could you help me explain this trade off?
 
Loss curve during the training Class-Module
 Besides, during the training, I find it that Class-loss decreases obviously. But Average-loss changes smoothly. Is this obversation normal?
 
 
 Waiting for your reply! Thanks for your time!
