### ISSUE TITLE
一个关于class module和probability vector的问题

### ISSUE THREAD

**Issue by LYX-ll** [XPixelGroup/ClassSR#54]
您好，我认为这是一个很不错的工作，我有一个问题想向您请教：
在论文中，提到通过class module生成概率向量（probability vector），请问概率向量是如何得到的，如何计算的？

**Comment by Xiangtaokong** [comment]
最后用fc层还是pooling映射到概率值，你看一下代码，一个简单的分类网络



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月3日(周二) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XPixelGroup/ClassSR] 一个关于class module和probability vector的问题 (Issue #54)




 
您好，我认为这是一个很不错的工作，我有一个问题想向您请教：
 在论文中，提到通过class module生成概率向量（probability vector），请问概率向量是如何得到的，如何计算的？
