### ISSUE TITLE
请问当训练ClassSR时，它联合训练的模型参数没有被optimize，导致只有class_loss下降，这种情况是否正常？如果异常，怎样修改呢？

### ISSUE THREAD

**Issue by nandubeigu** [XPixelGroup/ClassSR#56]
23-02-18 21:53:33.515 - WARNING: Params [module.net1.fea_conv.weight] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.fea_conv.bias] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c1_d.weight] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c1_d.bias] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c1_r.weight] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c1_r.bias] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c2_d.weight] will not optimize.
23-02-18 21:53:33.515 - WARNING: Params [module.net1.B1.c2_d.bias] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c2_r.weight] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c2_r.bias] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c3_d.weight] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c3_d.bias] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c3_r.weight] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c3_r.bias] will not optimize.
23-02-18 21:53:33.516 - WARNING: Params [module.net1.B1.c4.weight] will not optimize.

**Comment by Xiangtaokong** [comment]
有个参数 fix_SR_module: true 改成false

**Comment by nandubeigu** [comment]
Model               	Val PSNR  	Val Time [ms] 	Params [M]	FLOPs [G] 	Acts [M]	Mem [M] 	Conv    
00_RFDN_baseline    	28.74     	20.69         	0.433     	27.10     	112.03  	788.13  	  64    
-2_ClassRFDN_opt    	27.64     	14.46         	0.774     	3.37      	40.32   	675.04  	  69    
-2_ClassRFDN_opt_1  	27.64     	14.75         	0.774     	27.35     	114.26  	675.04  	  69    
-2_ClassRFDN_opt_2  	27.64     	15.04         	0.774     	14.63     	83.99   	675.04  	  69    
感谢回答，上一个问题解决，不过又碰到一个问题：我随便用一个训练出的模型数据跑了别人给的test_demo，结果发现同一个模型数据会跑出三种不同的flops和acts值，其他数值不变，请问原因是什么？

**Comment by Xiangtaokong** [comment]
这个数值部分不是ClassSR代码的输出，你可以看看是不是别的模型代码的输出。而且classsr输出的flops是写好了每个支路的flops然后乘图片数量（数量是动态的），改了结构需要重新自己算一下支路flops

**Comment by nandubeigu** [comment]
感谢大佬解惑，昨天研究了一下，应该是给定的test_demo代码测定的是随机支路的flops值，导致了flops值会出现三个不同的结果。
