### ISSUE TITLE
How can we get the dataset DIV8K

### ISSUE THREAD

**Issue by bowen480** [XPixelGroup/ClassSR#60]
I can not find the dataset called DIV8K from intenet

**Comment by Xiangtaokong** [comment]
https://competitions.codalab.org/competitions/22217#participate

**Comment by gonglujin** [comment]
您好，为什么注册进入页面后，没有看到获取数据的链接呢

**Comment by K-I-M-J-I-N** [comment]
@Xiangtaokong The CodaLab site is currently unavailable.... I think the server is closed. Is there another way?

**Comment by Xiangtaokong** [comment]
> @Xiangtaokong The CodaLab site is currently unavailable.... I think the server is closed. Is there another way?

Using this link http://data.vision.ee.ethz.ch/timofter/AIM19ExtremeSR/trainHR_001to200.zip and change the "001to200" to "201to400" "401to600" …………"1401to1500" for all the data.

**Comment by JiyouSeo** [comment]
@Xiangtaokong The link you provided is currently unavailable. Where can I download div8k dataset?

**Comment by nitec427** [comment]
Same problem here
